name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
  
    runs-on: macos-11
    
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update pod
        run: sudo gem update cocoapods --pre
        
      - name: Install Dependencies
        run: |
          cd My1A2BGame
          pod install --repo-update
        shell: bash

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
        
      - name: Build and test
        run: xcodebuild clean build test -workspace My1A2BGame/My1A2BGame.xcworkspace -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.0" ONLY_ACTIVE_ARCH=YES
     
