name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build-and-test:
  
    runs-on: macos-13
    
    timeout-minutes: 30

    steps:
     - name: Install yeetd to solve Xcode15 slowness
       run:
           wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
           sudo installer -pkg yeetd-normal.pkg -target /
           yeetd &
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app
        
      - name: Build and test
        run: xcodebuild clean build test -workspace My1A2BGame.xcworkspace -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0.1" ONLY_ACTIVE_ARCH=YES
     
